Repository GeeksCAT/nem-per-feina, pull requests merged in 2020-11, with the labels that each got.

#151 Add formspree.io service for contact form
  jobs/settings.py
  jobsapp/templates/contact_us.html
  jobsapp/utils.py
  manifests/env.yaml
Labels: backend, enhancement, frontend

#147 (#21) [New]: Cookie law
  jobs/settings.py
  jobsapp/templates/base.html
  requirements.txt
Labels: enhancement, frontend

#143 (#19) [New]: Captcha added
  .env.dev.sample
  .gitignore
  accounts/forms.py
  accounts/templates/accounts/register.html
  docker-compose.testing.yml
  jobs/settings.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/contact_us.html
  logs/debug.log.2020-02-17
  logs/debug.log.2020-07-30
  logs/debug.log.2020-08-11
  logs/no_commit_logs.txt
  requirements.txt
Labels: backend, enhancement

#160 Improved django views design
  static/css/custom.css
Labels: enhancement, frontend

#158 Creation job form improved
  jobs/settings.py
  jobsapp/forms.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/migrations/0014_auto_20201103_0431.py
  jobsapp/migrations/0015_job_salary.py
  jobsapp/models.py
  jobsapp/templates/home.html
  jobsapp/templates/jobsapp/create.html
  jobsapp/templates/jobsapp/details.html
  jobsapp/templates/jobsapp/employer/dashboard.html
  jobsapp/templates/jobsapp/update.html
  jobsapp/urls.py
  jobsapp/views/employer.py
  tests/factories.py
  tests/jobsapp/test_endpoints.py
Labels: backend, enhancement, frontend

#161 Translated using Weblate (Catalan)
  accounts/locale/ca/LC_MESSAGES/django.mo
  accounts/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
Labels: enhancement

#162 Translate Accounts module using Weblate (Catalan)
  accounts/locale/ca/LC_MESSAGES/django.mo
  accounts/locale/ca/LC_MESSAGES/django.po
Labels: backend, enhancement

#164 Translated using Weblate (Spanish)
  accounts/locale/es/LC_MESSAGES/django.mo
  accounts/locale/es/LC_MESSAGES/django.po
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
Labels: backend, enhancement

#177 Job's salary field changed to char field. Currency code removed from …
  jobsapp/migrations/0017_auto_20201104_1107.py
  jobsapp/migrations/0018_auto_20201104_1111.py
  jobsapp/models.py
  jobsapp/templates/jobsapp/details.html
  notifications/templates/notifications/telegram_new_job.html
  notifications/templates/notifications/twitter_new_job.html
  tests/factories.py
  tests/jobsapp/test_endpoints.py
Labels: backend, enhancement, frontend

#169 i18n for our contact form
  jobsapp/forms.py
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/contact_us.html
Labels: enhancement

#171 Add Github social buttons to the footer
  jobsapp/templates/base.html
  static/css/custom.css
Labels: backend, enhancement

#170 Fix flat pages
  jobs/urls.py
  jobsapp/admin.py
  jobsapp/templates/base.html
  jobsapp/urls.py
  templates/flatpages/default.html
Labels: backend, bug

#176 Fix Github social auth
  jobs/settings.py
Labels: backend, bug

#178 Translated using Weblate (Spanish)
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
Labels: backend

#179 Hotfix prod changes
  jobs/settings.py
  jobs/urls.py
Labels: backend, bug

#180 Language added to contact form for formspree
  jobsapp/forms.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/contact_us.html
Labels: bug, frontend

#181 Integrate new logo
  jobsapp/templates/base.html
  static/img/logo-small copy.png
  static/img/logo-small.png
  static/img/logo.png
Labels: backend

#182 Only show unfilled jobs at home
  jobsapp/managers.py
  jobsapp/models.py
  jobsapp/views/home.py
Labels: backend, enhancement, frontend

#183 Translated using Weblate (Catalan)
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
Labels: backend, enhancement

#184 Translated using Weblate (Spanish)
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
Labels: backend, enhancement

#185 Security fixes, permissions and other improvements
  jobsapp/forms.py
  jobsapp/templates/jobsapp/create.html
  jobsapp/views/employer.py
Labels: backend, bug

#186 Fix create description
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/jobsapp/create.html
Labels: backend, enhancement

#188 Sort languages (ca, es, en)
  jobs/settings.py
Labels: backend, enhancement

#189 Fix image link to offer
  jobsapp/templates/home.html
Labels: backend, enhancement

#191 Fix logo to "Nem per feina!"
  static/img/logo-hr.png
  static/img/logo-small copy.png
  static/img/logo-small.png
  static/img/logo.png
Labels: backend

#192 Change any reference to "Anem" -> "Nem"
  .all-contributorsrc
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.test
  README.md
  accounts/locale/ca/LC_MESSAGES/django.po
  accounts/locale/es/LC_MESSAGES/django.po
  docker-compose.testing.yml
  docker-compose.yml
  jobs/celery.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/base.html
  manifests/backend-worker.yaml
  manifests/backend.yaml
Labels: backend

#193 Add banner
  README.md
Labels: backend

#198 Permit "mailto://" schemes in job's apply url
  jobs/settings.py
  jobsapp/fields.py
  jobsapp/migrations/0019_auto_20201125_0939.py
  jobsapp/models.py
Labels: backend, enhancement

#201 Permit rich content for description fields //do not merge before #198
  jobs/settings.py
  jobs/urls.py
  jobsapp/fields.py
  jobsapp/migrations/0020_auto_20201125_1802.py
  jobsapp/models.py
  jobsapp/templates/base.html
  jobsapp/templates/home.html
  jobsapp/templates/jobsapp/create.html
  jobsapp/templates/jobsapp/details.html
  jobsapp/templatetags/bleach_extra_tags.py
  requirements.txt
  static/css/custom.css
Labels: backend, enhancement
