Repository GeeksCAT/nem-per-feina, pull requests merged in 2020-10, with the labels that each got.

#28 Fix desktop OS examples
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#41 (#25) [Fixed]: Code cleaned, PEP8 fies, improvements in settings
  .flake8
  .gitignore
  accounts/api/serializers.py
  accounts/api/views.py
  accounts/urls.py
  accounts/views.py
  jobs/settings.py
  jobsapp/api/urls.py
  jobsapp/api/views/__init__.py
  jobsapp/models.py
  jobsapp/urls.py
  jobsapp/views/__init__.py
  manage.py
Labels: dev, enhancement

#48 feat: App containerization: dockerfile and settings
  Dockerfile
  docker-entrypoint.sh
  jobs/settings/__init__.py
  jobs/settings/base.py
  jobs/settings/development.py
  jobs/settings/local.py
Labels: arch & CI

#45 Add django-environ to manage environment variables.
  jobs/settings/base.py
  requirements.txt
Labels: backend, enhancement

#54 Fix jobs settings
  jobs/settings/__init__.py
  jobs/settings/base.py
  jobs/settings/development.py
  jobs/settings/local.py
Labels: backend, enhancement

#56 (#55) [Fixed]: Environment variable names
  .env.dev.sample
  README.md
  jobs/settings/__init__.py
Labels: backend, enhancement

#51 Code linter and format with Black and Flake8
  .flake8
  .github/pull_request_template.md
  .github/workflows/pythonapp.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  accounts/admin.py
  accounts/api/custom_claims.py
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  accounts/apps.py
  accounts/forms.py
  accounts/managers.py
  accounts/models.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  jobs/settings/__init__.py
  jobs/settings/development.py
  jobs/urls.py
  jobs/wsgi.py
  jobsapp/admin.py
  jobsapp/api/custom_exception.py
  jobsapp/api/permissions.py
  jobsapp/api/serializers.py
  jobsapp/api/urls.py
  jobsapp/api/views/common.py
  jobsapp/api/views/employee.py
  jobsapp/api/views/employer.py
  jobsapp/apps.py
  jobsapp/decorators.py
  jobsapp/forms.py
  jobsapp/models.py
  jobsapp/templatetags/is_already_applied.py
  jobsapp/tests.py
  jobsapp/urls.py
  jobsapp/views/employee.py
  jobsapp/views/employer.py
  jobsapp/views/home.py
  manage.py
  pyproject.toml
  requirements-test.txt
Labels: backend, enhancement

#57 (#37) [Improvement]: sqlite database removed from repository
  .env.dev.sample
  .gitignore
  README.md
  accounts/fixtures/demo.json
  db.sqlite3
  jobs/settings/__init__.py
  jobsapp/fixtures/demo.json
Labels: backend, enhancement

#59 Implement typing test
  .github/workflows/pythonapp.yml
  checks.py
  requirements-test.txt
Labels: backend, enhancement

#64 Add delete view on employer dashboard
  jobsapp/urls.py
  jobsapp/views/employer.py
  templates/jobs/delete.html
  templates/jobs/employer/dashboard.html
Labels: backend

#65 Add Django-constance
  jobs/settings/__init__.py
Labels: backend, enhancement

#73 Fix development settings and clean import
  jobs/settings/development.py
  jobs/settings/testing.py
Labels: arch & CI

#79 Dispatch GH action on each PR
  .github/workflows/pythonapp.yml
Labels: arch & CI, backend, bug

#81 Massive code lint
  jobs/settings/testing.py
  jobsapp/views/employer.py
  tests/accounts/test_accounts.py
  tests/factories.py
  tests/jobsapp/test_jopsapp.py
Labels: arch & CI, backend, bug

#84 Mute mypy errors for "check-code" CI
  .github/workflows/code-check.yml
Labels: backend, enhancement

#87 Fix checks.py to be able to run in github-actions properly
  .github/workflows/code-check.yml
  checks.py
Labels: arch & CI, backend, bug

#63 feat: Docker-compose: add docker compose with App+PostgreSQL
  .dockerignore
  .env.dev.sample
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  docker/.env.dev.sample
  docker/config-env.sh
  docker/entrypoint.sh
  jobs/settings/development.py
  requirements.txt
Labels: arch & CI

#77 Add read requirements.txt in requirements-test.txt
  requirements-test.txt
Labels: backend, enhancement

#93 Add greetings on user first interaction
  .github/workflows/greetings.yml
Labels: backend, enhancement

#94 Feature/92 Provide Makefile
  .mk-lib/CHANGELOG.md
  .mk-lib/HEADER.mk
  .mk-lib/LICENSE
  .mk-lib/Makefile.minimal.mk
  .mk-lib/Makefile.sample.mk
  .mk-lib/README.md
  .mk-lib/common.mk
  .mk-lib/self-upgrade.sh
  .mk-lib/variables.mk
  .mk-lib/version.mk
  Dockerfile.test
  Makefile
  README.md
  docker-compose.yml
  tasks.py
Labels: arch & CI, backend, enhancement

#70 First approach to get models in adminsite
  accounts/admin.py
  jobsapp/admin.py
Labels: backend, enhancement

#96 (#83) [Fixed]: Mypy fixes in admin, models and manager accounts files.
  accounts/admin.py
  accounts/managers.py
  accounts/models.py
Labels: backend, enhancement

#71 Model fields info
  accounts/migrations/0003_auto_20201014_0629.py
  accounts/models.py
  jobsapp/migrations/0009_auto_20201014_0629.py
  jobsapp/models.py
Labels: backend, enhancement

#105 Added all-contributors section to README file
  .all-contributorsrc
  README.md
  package.json
Labels: documentation, enhancement

#103 Fix some mypy issues
  .github/workflows/code-check.yml
  .mypy.ini
  accounts/api/custom_claims.py
  accounts/api/serializers.py
  accounts/api/views.py
  accounts/managers.py
  accounts/models.py
  jobs/settings.py
  jobsapp/api/custom_exception.py
  jobsapp/api/permissions.py
  jobsapp/api/views/common.py
  jobsapp/api/views/employee.py
  jobsapp/api/views/employer.py
  jobsapp/models.py
  requirements-test.txt
  tasks.py
  tests/__init__.py
  tests/accounts/test_accounts.py
  tests/factories.py
  tests/factories.pyi
  tests/jobsapp/test_jopsapp.py
Labels: backend

#115 Disable on pull_request due build errors
  .github/workflows/greetings.yml
Labels: bug

#114 Ignore node_modules
  .gitignore
Labels: enhancement

#113 Sentry setup
  .env.dev.sample
  jobs/settings.py
  requirements.txt
  tests/pytest.ini
Labels: arch & CI, backend

#98 Provide initial manifest.yaml
  README.md
  manifests/README.md
  manifests/backend.yaml
  manifests/db.yaml
  manifests/env.yaml
  manifests/public.yaml
  manifests/secrets.yaml
Labels: arch & CI, backend, enhancement

#120 Adding celery integration in sentry and add False as default
  jobs/settings.py
Labels: backend, bug

#123 Username attribute reverted
  accounts/models.py
Labels: backend, bug

#111 Feature/provide i18n
  CONTRIBUTING.md
  README.md
  accounts/locale/ca/LC_MESSAGES/django.po
  accounts/locale/es/LC_MESSAGES/django.po
  jobs/settings.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
Labels: backend, enhancement

#126 Update CA translations
  accounts/locale/ca/LC_MESSAGES/django.mo
  accounts/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
Labels: enhancement

#118 Add gettext to views
  accounts/api/serializers.py
  accounts/api/views.py
  accounts/forms.py
  accounts/locale/ca/LC_MESSAGES/django.po
  accounts/locale/es/LC_MESSAGES/django.po
  accounts/models.py
  accounts/views.py
  jobsapp/forms.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/views/employee.py
  jobsapp/views/employer.py
  jobsapp/views/home.py
Labels: backend, enhancement

#110 (#8) [New]: Notification system
  .gitignore
  docker-compose.yml
  jobs/celery.py
  jobs/settings.py
  jobsapp/models.py
  notifications/README.md
  notifications/__init__.py
  notifications/apps.py
  notifications/decorators.py
  notifications/events.py
  notifications/exceptions.py
  notifications/providers/__init__.py
  notifications/providers/base.py
  notifications/providers/telegram.py
  notifications/providers/twitter.py
  notifications/settings.py
  notifications/tasks.py
  notifications/templates/notifications/telegram_new_job.html
  notifications/templates/notifications/twitter_new_job.html
  requirements.txt
  tasks.py
  tests/conftest.py
  tests/notifications/test_notifications.py
Labels: backend, enhancement

#127 Add spanish translations
  accounts/locale/ca/LC_MESSAGES/django.mo
  accounts/locale/ca/LC_MESSAGES/django.po
  accounts/locale/es/LC_MESSAGES/django.mo
  accounts/locale/es/LC_MESSAGES/django.po
  jobsapp/locale/ca/LC_MESSAGES/django.mo
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.mo
  jobsapp/locale/es/LC_MESSAGES/django.po
Labels: backend, enhancement

#125 Add SonarCloud to GitHub Actions
  .github/workflows/sonar-analysis.yml
  sonar-project.properties
Labels: backend, isec

#112 Update README.md make test command
  README.md
Labels: backend, documentation

#130 Add celery to k8s
  .env.dev.sample
  jobs/settings.py
  manifests/backend-worker.yaml
  manifests/env.yaml
Labels: enhancement

#124 (#1) Add support for Github login
  jobs/settings.py
  jobs/urls.py
  requirements.txt
  templates/accounts/login.html
Labels: backend, frontend

#116 #108 Simplify models
  accounts/admin.py
  accounts/api/serializers.py
  accounts/fixtures/demo.json
  accounts/forms.py
  accounts/migrations/0004_remove_user_role.py
  accounts/models.py
  accounts/urls.py
  accounts/views.py
  jobsapp/admin.py
  jobsapp/api/permissions.py
  jobsapp/api/serializers.py
  jobsapp/api/urls.py
  jobsapp/api/views/employee.py
  jobsapp/api/views/employer.py
  jobsapp/decorators.py
  jobsapp/fixtures/demo.json
  jobsapp/forms.py
  jobsapp/migrations/0010_delete_applicant.py
  jobsapp/models.py
  jobsapp/templatetags/is_already_applied.py
  jobsapp/urls.py
  jobsapp/views/employer.py
  jobsapp/views/home.py
  templates/accounts/employee/register.html
  templates/base.html
  templates/jobs/details.html
  templates/jobs/employer/all-applicants.html
  templates/jobs/employer/applicants.html
  templates/jobs/employer/dashboard.html
  tests/accounts/test_accounts.py
Labels: backend, enhancement

#121 Fix tests, now make test is working and add missed migration
  .env.dev.sample
  .github/workflows/check-pr.yml
  .github/workflows/greetings.yml
  .mk-lib/variables.mk
  Dockerfile.test
  Makefile
  docker-compose.testing.yml
  docker-compose.yml
  pytest.ini
  tasks.py
  tests/pytest.ini
Labels: arch & CI, backend

#131 Add makemigrations to Makefile
  Makefile
Labels: arch & CI, enhancement

#138 Add Telegram notification provider
  .env.dev.sample
  jobs/settings.py
  jobsapp/models.py
  manifests/backend-worker.yaml
  manifests/backend.yaml
  manifests/env.yaml
  manifests/secrets.yaml
  notifications/locale/ca/LC_MESSAGES/django.mo
  notifications/locale/ca/LC_MESSAGES/django.po
  notifications/locale/es/LC_MESSAGES/django.mo
  notifications/locale/es/LC_MESSAGES/django.po
  notifications/providers/base.py
  notifications/providers/telegram.py
  notifications/templates/notifications/telegram_new_job.html
  requirements.txt
Labels: enhancement

#137 (#129) [New]: Language selector and template literals translated
  accounts/locale/ca/LC_MESSAGES/django.po
  accounts/locale/es/LC_MESSAGES/django.po
  accounts/templates/accounts/login.html
  accounts/templates/accounts/register.html
  accounts/views.py
  jobs/settings.py
  jobs/urls.py
  jobsapp/locale/ca/LC_MESSAGES/django.po
  jobsapp/locale/es/LC_MESSAGES/django.po
  jobsapp/templates/base.html
  jobsapp/templates/home.html
  jobsapp/templates/includes/lang_selector.html
  jobsapp/templates/jobsapp/create.html
  jobsapp/templates/jobsapp/delete.html
  jobsapp/templates/jobsapp/details.html
  jobsapp/templates/jobsapp/employee/edit-profile.html
  jobsapp/templates/jobsapp/employer/dashboard.html
  jobsapp/templates/jobsapp/jobs.html
  jobsapp/templates/jobsapp/search.html
  jobsapp/views/employee.py
  jobsapp/views/employer.py
  jobsapp/views/home.py
  templates/accounts/employer/register.html
  templates/accounts/login.html
  templates/base.html
  templates/home.html
  templates/jobs/create.html
  templates/jobs/delete.html
  templates/jobs/details.html
  templates/jobs/employee/edit-profile.html
  templates/jobs/employer/dashboard.html
  templates/jobs/jobs.html
  templates/jobs/search.html
Labels: backend, enhancement

#139 Add "contact us" api endpoint
  .env.dev.sample
  docker-compose.testing.yml
  jobs/settings.py
  jobsapp/api/serializers.py
  jobsapp/api/urls.py
  jobsapp/api/views/common.py
  jobsapp/tasks.py
  jobsapp/utils.py
  tests/conftest.py
  tests/jobsapp/test_endpoints.py
Labels: backend

#142 Feature/141 add twitter provider
  .env.dev.sample
  jobs/settings.py
  manifests/backend-worker.yaml
  manifests/backend.yaml
  manifests/env.yaml
  manifests/secrets.yaml
  notifications/providers/base.py
  notifications/providers/twitter.py
  notifications/templates/notifications/twitter_new_job.html
  requirements.txt
Labels: enhancement

#144 Add About us page
  jobs/settings.py
  jobs/urls.py
  jobsapp/admin.py
  jobsapp/api/urls.py
  jobsapp/api/views/common.py
  jobsapp/templates/base.html
  templates/flatpages/about-us.html
  tests/jobsapp/test_endpoints.py
Labels: backend, frontend

#145 Add EMAIL envs to our Manifest
  .env.dev.sample
  jobs/settings.py
  manifests/env.yaml
  manifests/secrets.yaml
Labels: enhancement

#146 Add "contact us" form to front-end page
  jobs/settings.py
  jobsapp/forms.py
  jobsapp/templates/base.html
  jobsapp/templates/contact_us.html
  jobsapp/urls.py
  jobsapp/views/home.py
Labels: backend, frontend

#148 Missing default email settings added
  jobs/settings.py
Labels: backend, bug

#149 Simplify api endpoints
  accounts/api/urls.py
  jobs/settings.py
  jobsapp/api/permissions.py
  jobsapp/api/serializers.py
  jobsapp/api/urls.py
  jobsapp/api/views/common.py
  jobsapp/api/views/jobs.py
  jobsapp/api/views/users.py
  jobsapp/migrations/0011_auto_20201030_1636.py
  jobsapp/migrations/0012_job_salary.py
  jobsapp/migrations/0013_job_remote.py
  jobsapp/models.py
  requirements-test.txt
  requirements.txt
  tests/conftest.py
  tests/factories.py
  tests/jobsapp/test_endpoints.py
  tests/pytest.ini
Labels: backend
